## @section Global parameters
## Please, note that this will override the parameters, including dependencies, configured to use the global value
##
global:
  storageClass: "ebs-csi-gp3"
  postgresql:
    auth:
      database: "cloudtrain"
      existingSecret: "cnj-tracing-resources-postgres"
      secretKeys:
        adminPasswordKey: "postgresql-postgres-password"
        userPasswordKey: "postgresql-password"
        replicationPasswordKey: ""

postgresql:
  auth:
    enablePostgresUser: true
    username: "replace_me"
  primary:
    livenessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
    startupProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 15
      successThreshold: 1
    resources:
      limits: {}
      requests:
        memory: 256Mi
        cpu: 250m
    podSecurityContext:
      enabled: true
      fsGroup: 1001
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
    podAntiAffinityPreset: soft
    persistence:
      enabled: true
      size: 8Gi
  networkPolicy:
    enabled: false
    metrics:
      enabled: false
      namespaceSelector: {}
      podSelector: {}
    ingressRules:
      primaryAccessOnlyFrom:
        enabled: false
        namespaceSelector: {}
        podSelector: {}
        customRules: []
      readReplicasAccessOnlyFrom:
        enabled: false
        namespaceSelector: {}
        podSelector: {}
        customRules: []
    egressRules:
      denyConnectionsToExternal: false
      customRules: []
  serviceAccount:
    create: true
    automountServiceAccountToken: true
    annotations: {}
  rbac:
    create: false
  psp:
    create: false
  metrics:
    enabled: true
    customMetrics: {}
    extraEnvVars: []
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true
    livenessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
    startupProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 15
      successThreshold: 1
    resources:
      limits: {}
      requests: {}
    serviceMonitor:
      enabled: true
