---
kind: pipeline
type: kubernetes
name: cnj-tracing-build

steps:
  - name: resources-integration-test-stage
    image: docker.cloudtrain.aws.msgoat.eu/cloudtrain/cnj-drone-build:2.0.2
    pull: always
    environment:
      POSTGRES_ADMIN_PASSWORD:
        from_secret: postgres_admin_password
      POSTGRES_USER_NAME:
        from_secret: postgres_user_name
      POSTGRES_USER_PASSWORD:
        from_secret: postgres_user_password
    commands:
      - mvn clean install -f pom.xml -B -ff -e -V -U -P  integration-test-stage -Dchangelist=.${DRONE_BRANCH} -Dsha1=.${DRONE_COMMIT_SHA:0:8}
